In [1]:
import numpy
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
import tensorflow as tf
 
import keras

Using TensorFlow backend.


In [2]:
numpy.random.seed(42)
 
(X_train, y_train), (X_test, y_test) = keras.datasets.mnist.load_data()


In [3]:
X_train = X_train.reshape(60000, 784)
X_train = X_train.astype('float32')
X_train /= 255

y_train = np_utils.to_categorical(y_train, 10)

In [4]:
model = Sequential()


In [5]:
model.add(Dense(800, input_dim = 784, init = "normal", activation = "relu"))



/home/natalya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(800, input_dim=784, activation="relu", kernel_initializer="normal")`
  """Entry point for launching an IPython kernel.


In [6]:

model.add(Dense(10, init="normal", activation="softmax"))




/home/natalya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(10, activation="softmax", kernel_initializer="normal")`
  


In [7]:
keras.__version__


'2.2.4'

In [8]:
tf.__version__


'1.10.0'

In [9]:
model.compile(loss="categorical_crossentropy", optimizer="SGD", metrics=["accuracy"])

In [10]:
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 800)               628000    
_________________________________________________________________
dense_2 (Dense)              (None, 10)                8010      
Total params: 636,010
Trainable params: 636,010
Non-trainable params: 0
_________________________________________________________________
None


In [11]:
model.fit(X_train, y_train, batch_size=200, nb_epoch=100, verbose=1)


/home/natalya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/100
60000/60000 [==============================] - 6s 93us/step - loss: 1.2037 - acc: 0.7260
Epoch 2/100
60000/60000 [==============================] - 5s 91us/step - loss: 0.5962 - acc: 0.8620
Epoch 3/100
60000/60000 [==============================] - 5s 91us/step - loss: 0.4728 - acc: 0.8807
Epoch 4/100
60000/60000 [==============================] - 5s 91us/step - loss: 0.4165 - acc: 0.8910
Epoch 5/100
60000/60000 [==============================] - 6s 92us/step - loss: 0.3826 - acc: 0.8980
Epoch 6/100
60000/60000 [==============================] - 6s 92us/step - loss: 0.3593 - acc: 0.9027
Epoch 7/100
60000/60000 [==============================] - 6s 94us/step - loss: 0.3418 - acc: 0.9062
Epoch 8/100
60000/60000 [==============================] - 6s 93us/step - loss: 0.3279 - acc: 0.9096
Epoch 9/100
60000/60000 [==============================] - 6s 93us/step - loss: 0.3162 - acc: 0.9122
Epoch 10/100
60000/60000 [==============================] - 6s 92us/step - loss: 0.3062 - a

60000/60000 [==============================] - 5s 91us/step - loss: 0.1186 - acc: 0.9683
Epoch 82/100
60000/60000 [==============================] - 5s 92us/step - loss: 0.1176 - acc: 0.9684
Epoch 83/100
60000/60000 [==============================] - 5s 92us/step - loss: 0.1166 - acc: 0.9685
Epoch 84/100
60000/60000 [==============================] - 5s 91us/step - loss: 0.1157 - acc: 0.9690
Epoch 85/100
60000/60000 [==============================] - 5s 91us/step - loss: 0.1147 - acc: 0.9694
Epoch 86/100
60000/60000 [==============================] - 5s 91us/step - loss: 0.1137 - acc: 0.9694
Epoch 87/100
60000/60000 [==============================] - 5s 89us/step - loss: 0.1128 - acc: 0.9695
Epoch 88/100
60000/60000 [==============================] - 5s 89us/step - loss: 0.1119 - acc: 0.9699
Epoch 89/100
60000/60000 [==============================] - 5s 90us/step - loss: 0.1110 - acc: 0.9702
Epoch 90/100
60000/60000 [==============================] - 5s 90us/step - loss: 0.1101 - acc: 

In [13]:
predictions = model.predict(X_train)



In [14]:
predictions[0]

array([6.8084237e-06, 6.0998605e-06, 2.6102032e-04, 1.0871841e-02,
       3.5629930e-09, 9.8881578e-01, 3.1163762e-07, 2.7594480e-05,
       3.0337649e-06, 7.4352238e-06], dtype=float32)

In [15]:
result = predictions.argmax(axis=1)

In [16]:
result

array([5, 0, 4, ..., 5, 6, 8])

In [17]:
y_train.argmax(axis=1)

array([5, 0, 4, ..., 5, 6, 8])